apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-pipeline-run-
spec:
  pipelineRef:
    name: buildah-tekton-pipeline
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/peter-christian-buildah-app-v2
    - name: image-repo
      value: quay.io/petercur/buildah-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
